# 3.1 Import Libraries

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# 3.2 Load All CSV Files

In [3]:
import os
import glob

path = "dataset"

csv_files = glob.glob(os.path.join(path, "*.csv"))

print(csv_files)

[]

# 3.3 Merge All Files

In [4]:
df = pd.concat(
    (pd.read_csv(file, low_memory=False) for file in csv_files),
    ignore_index=True
)

ValueError: No objects to concatenate

# 3.4 Basic Information

In [12]:
print(df.shape)

(2830743, 79)

First Five Rows and Last Five Rows

In [15]:
df.head()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,4.000000e+06,666666.66670,3.0,0.0,3,3,3,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0,0,0,40,0,666666.666700,0.000000,6,6,6.0,0.0,0.0,0,0,0,0,1,0,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,33,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.0,6,6,6.0,0.0,1.100917e+05,18348.62385,109.0,0.0,109,109,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,9174.311927,9174.311927,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,1,9.0,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,29,256,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.0,6,6,6.0,0.0,2.307692e+05,38461.53846,52.0,0.0,52,52,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,19230.769230,19230.769230,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,1,9.0,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,29,256,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.0,6,6,6.0,0.0,3.529412e+05,58823.52941,34.0,0.0,34,34,0,0.0,0.0,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,29411.764710,29411.764710,6,6,6.0,0.0,0.0,0,0,0,0,1,1,0,0,1,9.0,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,31,329,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.0,0,0,0.0,0.0,4.000000e+06,666666.66670,3.0,0.0,3,3,3,3.0,0.0,3,3,0,0.0,0.0,0,0,0,0,0,0,40,0,666666.666700,0.000000,6,6,6.0,0.0,0.0,0,0,0,0,1,0,0,0,0,9.0,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,32,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [14]:
df.tail()

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
2830738,53,32215,4,2,112,152,28,28,28.0,0.00000,76,76,76.0,0.0,8.194940e+03,186.248642,6443.0,13617.579480,30780,3,30832,10277.33333,17755.84381,30780,4,3,3.0,0.0,3,3,0,0,0,0,80,64,124.165761,62.082881,28,76,41.714286,23.421602,548.571429,0,0,0,0,0,0,0,0,0,48.666667,28.0,76.0,80,0,0,0,0,0,0,4,112,2,152,-1,-1,3,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2830739,53,324,2,2,84,362,42,42,42.0,0.00000,181,181,181.0,0.0,1.376543e+06,12345.679010,108.0,183.597386,320,2,2,2.00000,0.00000,2,2,2,2.0,0.0,2,2,0,0,0,0,40,40,6172.839506,6172.839506,42,181,97.600000,76.133435,5796.300000,0,0,0,0,0,0,0,0,1,122.000000,42.0,181.0,40,0,0,0,0,0,0,2,84,2,362,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2830740,58030,82,2,1,31,6,31,0,15.5,21.92031,6,6,6.0,0.0,4.512195e+05,36585.365850,41.0,52.325902,78,4,4,4.00000,0.00000,4,4,0,0.0,0.0,0,0,1,0,0,0,64,20,24390.243900,12195.121950,0,31,17.000000,16.350331,267.333333,0,1,0,0,1,0,0,0,0,22.666667,15.5,6.0,64,0,0,0,0,0,0,2,31,1,6,1006,0,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2830741,53,1048635,6,2,192,256,32,32,32.0,0.00000,128,128,128.0,0.0,4.272221e+02,7.628965,149805.0,375521.040500,1000947,1,1033613,206722.60000,444210.06860,1000947,1,3,3.0,0.0,3,3,0,0,0,0,120,40,5.721724,1.907241,32,128,53.333333,42.332021,1792.000000,0,0,0,0,0,0,0,0,0,60.000000,32.0,128.0,120,0,0,0,0,0,0,6,192,2,256,-1,-1,5,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2830742,53,94939,4,2,188,226,47,47,47.0,0.00000,113,113,113.0,0.0,4.360695e+03,63.198475,18987.8,31664.102560,73049,1,73051,24350.33333,42174.28246,73049,1,48,48.0,0.0,48,48,0,0,0,0,104,64,42.132317,21.066158,47,113,65.857143,32.204702,1037.142857,0,0,0,0,0,0,0,0,0,76.833333,47.0,113.0,104,0,0,0,0,0,0,4,188,2,226,-1,-1,3,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [16]:
df.columns.tolist()

[' Destination Port',
 ' Flow Duration',
 ' Total Fwd Packets',
 ' Total Backward Packets',
 'Total Length of Fwd Packets',
 ' Total Length of Bwd Packets',
 ' Fwd Packet Length Max',
 ' Fwd Packet Length Min',
 ' Fwd Packet Length Mean',
 ' Fwd Packet Length Std',
 'Bwd Packet Length Max',
 ' Bwd Packet Length Min',
 ' Bwd Packet Length Mean',
 ' Bwd Packet Length Std',
 'Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Total',
 ' Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Total',
 ' Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Fwd PSH Flags',
 ' Bwd PSH Flags',
 ' Fwd URG Flags',
 ' Bwd URG Flags',
 ' Fwd Header Length',
 ' Bwd Header Length',
 'Fwd Packets/s',
 ' Bwd Packets/s',
 ' Min Packet Length',
 ' Max Packet Length',
 ' Packet Length Mean',
 ' Packet Length Std',
 ' Packet Length Variance',
 'FIN Flag Count',
 ' SYN Flag Count',
 ' RST Flag Count',
 ' PSH Flag Count',
 ' ACK Flag Count',
 ' URG Flag Count',
 ' CWE Flag Count',
 ' ECE Flag Count',
 ' Down/Up Ratio',
 ' Average Packet Size',
 ' Avg Fwd Segment Size',
 ' Avg Bwd Segment Size',
 ' Fwd Header Length.1',
 'Fwd Avg Bytes/Bulk',
 ' Fwd Avg Packets/Bulk',
 ' Fwd Avg Bulk Rate',
 ' Bwd Avg Bytes/Bulk',
 ' Bwd Avg Packets/Bulk',
 'Bwd Avg Bulk Rate',
 'Subflow Fwd Packets',
 ' Subflow Fwd Bytes',
 ' Subflow Bwd Packets',
 ' Subflow Bwd Bytes',
 'Init_Win_bytes_forward',
 ' Init_Win_bytes_backward',
 ' act_data_pkt_fwd',
 ' min_seg_size_forward',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min',
 ' Label']

In [17]:
df.columns = df.columns.str.strip()

In [18]:
df.dtypes

Destination Port                 int64
Flow Duration                    int64
Total Fwd Packets                int64
Total Backward Packets           int64
Total Length of Fwd Packets      int64
Total Length of Bwd Packets      int64
Fwd Packet Length Max            int64
Fwd Packet Length Min            int64
Fwd Packet Length Mean         float64
Fwd Packet Length Std          float64
Bwd Packet Length Max            int64
Bwd Packet Length Min            int64
Bwd Packet Length Mean         float64
Bwd Packet Length Std          float64
Flow Bytes/s                   float64
Flow Packets/s                 float64
Flow IAT Mean                  float64
Flow IAT Std                   float64
Flow IAT Max                     int64
Flow IAT Min                     int64
Fwd IAT Total                    int64
Fwd IAT Mean                   float64
Fwd IAT Std                    float64
Fwd IAT Max                      int64
Fwd IAT Min                      int64
Bwd IAT Total                    int64
Bwd IAT Mean                   float64
Bwd IAT Std                    float64
Bwd IAT Max                      int64
Bwd IAT Min                      int64
Fwd PSH Flags                    int64
Bwd PSH Flags                    int64
Fwd URG Flags                    int64
Bwd URG Flags                    int64
Fwd Header Length                int64
Bwd Header Length                int64
Fwd Packets/s                  float64
Bwd Packets/s                  float64
Min Packet Length                int64
Max Packet Length                int64
Packet Length Mean             float64
Packet Length Std              float64
Packet Length Variance         float64
FIN Flag Count                   int64
SYN Flag Count                   int64
RST Flag Count                   int64
PSH Flag Count                   int64
ACK Flag Count                   int64
URG Flag Count                   int64
CWE Flag Count                   int64
ECE Flag Count                   int64
Down/Up Ratio                    int64
Average Packet Size            float64
Avg Fwd Segment Size           float64
Avg Bwd Segment Size           float64
Fwd Header Length.1              int64
Fwd Avg Bytes/Bulk               int64
Fwd Avg Packets/Bulk             int64
Fwd Avg Bulk Rate                int64
Bwd Avg Bytes/Bulk               int64
Bwd Avg Packets/Bulk             int64
Bwd Avg Bulk Rate                int64
Subflow Fwd Packets              int64
Subflow Fwd Bytes                int64
Subflow Bwd Packets              int64
Subflow Bwd Bytes                int64
Init_Win_bytes_forward           int64
Init_Win_bytes_backward          int64
act_data_pkt_fwd                 int64
min_seg_size_forward             int64
Active Mean                    float64
Active Std                     float64
Active Max                       int64
Active Min                       int64
Idle Mean                      float64
Idle Std                       float64
Idle Max                         int64
Idle Min                         int64
Label                              str
dtype: object

# 3.5 Missing Values

In [19]:
missing = df.isnull().sum()

missing = missing[missing > 0]

print(missing.sort_values(ascending=False))

Flow Bytes/s    1358
dtype: int64

In [20]:
missing_percent = (df.isnull().sum()/len(df))*100

missing_percent = missing_percent[missing_percent>0]

print(missing_percent.sort_values(ascending=False))

Flow Bytes/s    0.047973
dtype: float64

# 3.6 Duplicate Rows

In [21]:
print(df.duplicated().sum())

308381

# 3.7 Check Infinite Values

In [22]:
numeric_df = df.select_dtypes(include=np.number)

print(np.isinf(numeric_df).sum())

Destination Port                  0
Flow Duration                     0
Total Fwd Packets                 0
Total Backward Packets            0
Total Length of Fwd Packets       0
Total Length of Bwd Packets       0
Fwd Packet Length Max             0
Fwd Packet Length Min             0
Fwd Packet Length Mean            0
Fwd Packet Length Std             0
Bwd Packet Length Max             0
Bwd Packet Length Min             0
Bwd Packet Length Mean            0
Bwd Packet Length Std             0
Flow Bytes/s                   1509
Flow Packets/s                 2867
Flow IAT Mean                     0
Flow IAT Std                      0
Flow IAT Max                      0
Flow IAT Min                      0
Fwd IAT Total                     0
Fwd IAT Mean                      0
Fwd IAT Std                       0
Fwd IAT Max                       0
Fwd IAT Min                       0
Bwd IAT Total                     0
Bwd IAT Mean                      0
Bwd IAT Std                       0
Bwd IAT Max                       0
Bwd IAT Min                       0
Fwd PSH Flags                     0
Bwd PSH Flags                     0
Fwd URG Flags                     0
Bwd URG Flags                     0
Fwd Header Length                 0
Bwd Header Length                 0
Fwd Packets/s                     0
Bwd Packets/s                     0
Min Packet Length                 0
Max Packet Length                 0
Packet Length Mean                0
Packet Length Std                 0
Packet Length Variance            0
FIN Flag Count                    0
SYN Flag Count                    0
RST Flag Count                    0
PSH Flag Count                    0
ACK Flag Count                    0
URG Flag Count                    0
CWE Flag Count                    0
ECE Flag Count                    0
Down/Up Ratio                     0
Average Packet Size               0
Avg Fwd Segment Size              0
Avg Bwd Segment Size              0
Fwd Header Length.1               0
Fwd Avg Bytes/Bulk                0
Fwd Avg Packets/Bulk              0
Fwd Avg Bulk Rate                 0
Bwd Avg Bytes/Bulk                0
Bwd Avg Packets/Bulk              0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
Subflow Fwd Bytes                 0
Subflow Bwd Packets               0
Subflow Bwd Bytes                 0
Init_Win_bytes_forward            0
Init_Win_bytes_backward           0
act_data_pkt_fwd                  0
min_seg_size_forward              0
Active Mean                       0
Active Std                        0
Active Max                        0
Active Min                        0
Idle Mean                         0
Idle Std                          0
Idle Max                          0
Idle Min                          0
dtype: int64

# 3.8 Target Column

In [23]:
print(df["Label"].unique())

<StringArray>
[                    'BENIGN',                       'DDoS',
                        'Bot',                   'PortScan',
               'Infiltration',   'Web Attack � Brute Force',
           'Web Attack � XSS', 'Web Attack � Sql Injection',
                'FTP-Patator',                'SSH-Patator',
              'DoS slowloris',           'DoS Slowhttptest',
                   'DoS Hulk',              'DoS GoldenEye',
                 'Heartbleed']
Length: 15, dtype: str

In [24]:
df["Label"].value_counts()

Label
BENIGN                        2273097
DoS Hulk                       231073
PortScan                       158930
DDoS                           128027
DoS GoldenEye                   10293
FTP-Patator                      7938
SSH-Patator                      5897
DoS slowloris                    5796
DoS Slowhttptest                 5499
Bot                              1966
Web Attack � Brute Force         1507
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [25]:
(df["Label"].value_counts(normalize=True)*100).round(2)

Label
BENIGN                        80.30
DoS Hulk                       8.16
PortScan                       5.61
DDoS                           4.52
DoS GoldenEye                  0.36
FTP-Patator                    0.28
SSH-Patator                    0.21
DoS slowloris                  0.20
DoS Slowhttptest               0.19
Bot                            0.07
Web Attack � Brute Force       0.05
Web Attack � XSS               0.02
Infiltration                   0.00
Web Attack � Sql Injection     0.00
Heartbleed                     0.00
Name: proportion, dtype: float64

# 3.9 Statistical Summary

In [26]:
df.describe().T

c:\Users\nimma\Downloads\IDS-PROJECT\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\nimma\Downloads\IDS-PROJECT\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,count,mean,std,min,25%,50%,75%,max
Destination Port,2830743.0,8.071483e+03,1.828363e+04,0.000000e+00,53.000000,80.000000,4.430000e+02,6.553500e+04
Flow Duration,2830743.0,1.478566e+07,3.365374e+07,-1.300000e+01,155.000000,31316.000000,3.204828e+06,1.200000e+08
Total Fwd Packets,2830743.0,9.361160e+00,7.496728e+02,1.000000e+00,2.000000,2.000000,5.000000e+00,2.197590e+05
Total Backward Packets,2830743.0,1.039377e+01,9.973883e+02,0.000000e+00,1.000000,2.000000,4.000000e+00,2.919220e+05
Total Length of Fwd Packets,2830743.0,5.493024e+02,9.993589e+03,0.000000e+00,12.000000,62.000000,1.870000e+02,1.290000e+07
Total Length of Bwd Packets,2830743.0,1.616264e+04,2.263088e+06,0.000000e+00,0.000000,123.000000,4.820000e+02,6.554530e+08
Fwd Packet Length Max,2830743.0,2.075999e+02,7.171848e+02,0.000000e+00,6.000000,37.000000,8.100000e+01,2.482000e+04
Fwd Packet Length Min,2830743.0,1.871366e+01,6.033935e+01,0.000000e+00,0.000000,2.000000,3.600000e+01,2.325000e+03
Fwd Packet Length Mean,2830743.0,5.820194e+01,1.860912e+02,0.000000e+00,6.000000,34.000000,5.000000e+01,5.940857e+03
Fwd Packet Length Std,2830743.0,6.891013e+01,2.811871e+02,0.000000e+00,0.000000,0.000000,2.616295e+01,7.125597e+03
Bwd Packet Length Max,2830743.0,8.708495e+02,1.946367e+03,0.000000e+00,0.000000,79.000000,2.800000e+02,1.953000e+04
Bwd Packet Length Min,2830743.0,4.104958e+01,6.886260e+01,0.000000e+00,0.000000,0.000000,7.700000e+01,2.896000e+03
Bwd Packet Length Mean,2830743.0,3.059493e+02,6.052568e+02,0.000000e+00,0.000000,72.000000,1.810000e+02,5.800500e+03
Bwd Packet Length Std,2830743.0,3.353257e+02,8.396932e+02,0.000000e+00,0.000000,0.000000,7.794054e+01,8.194660e+03
Flow Bytes/s,2829385.0,inf,NaN,-2.610000e+08,119.319731,4595.549126,1.666667e+05,inf
Flow Packets/s,2830743.0,inf,NaN,-2.000000e+06,3.446226,110.668437,2.325581e+04,inf
Flow IAT Mean,2830743.0,1.298449e+06,4.507944e+06,-1.300000e+01,63.666667,11438.842110,3.374266e+05,1.200000e+08
Flow IAT Std,2830743.0,2.919271e+06,8.045870e+06,0.000000e+00,0.000000,137.178716,6.912663e+05,8.480026e+07
Flow IAT Max,2830743.0,9.182475e+06,2.445954e+07,-1.300000e+01,123.000000,30865.000000,2.440145e+06,1.200000e+08
Flow IAT Min,2830743.0,1.623796e+05,2.950282e+06,-1.400000e+01,3.000000,4.000000,6.400000e+01,1.200000e+08
Fwd IAT Total,2830743.0,1.448296e+07,3.357581e+07,0.000000e+00,0.000000,43.000000,1.242844e+06,1.200000e+08
Fwd IAT Mean,2830743.0,2.610193e+06,9.525722e+06,0.000000e+00,0.000000,26.000000,2.063064e+05,1.200000e+08
Fwd IAT Std,2830743.0,3.266957e+06,9.639055e+06,0.000000e+00,0.000000,0.000000,6.598982e+04,8.460293e+07
Fwd IAT Max,2830743.0,9.042939e+06,2.452916e+07,0.000000e+00,0.000000,43.000000,9.310060e+05,1.200000e+08
Fwd IAT Min,2830743.0,1.021893e+06,8.591436e+06,-1.200000e+01,0.000000,3.000000,4.800000e+01,1.200000e+08
Bwd IAT Total,2830743.0,9.893830e+06,2.873661e+07,0.000000e+00,0.000000,3.000000,9.858050e+04,1.200000e+08
Bwd IAT Mean,2830743.0,1.805784e+06,8.887197e+06,0.000000e+00,0.000000,3.000000,1.824857e+04,1.200000e+08
Bwd IAT Std,2830743.0,1.485973e+06,6.278469e+06,0.000000e+00,0.000000,0.000000,1.572409e+04,8.441801e+07
Bwd IAT Max,2830743.0,4.684692e+06,1.716095e+07,0.000000e+00,0.000000,3.000000,6.021000e+04,1.200000e+08
Bwd IAT Min,2830743.0,9.672614e+05,8.308983e+06,0.000000e+00,0.000000,1.000000,4.500000e+01,1.200000e+08
Fwd PSH Flags,2830743.0,4.644646e-02,2.104500e-01,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
Bwd PSH Flags,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Fwd URG Flags,2830743.0,1.112782e-04,1.054826e-02,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
Bwd URG Flags,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Fwd Header Length,2830743.0,-2.599739e+04,2.105286e+07,-3.221223e+10,40.000000,64.000000,1.200000e+02,4.644908e+06
Bwd Header Length,2830743.0,-2.273275e+03,1.452209e+06,-1.073741e+09,20.000000,40.000000,1.040000e+02,5.838440e+06
Fwd Packets/s,2830743.0,6.386535e+04,2.475371e+05,0.000000e+00,1.749446,61.325238,1.204819e+04,3.000000e+06
Bwd Packets/s,2830743.0,6.995192e+03,3.815170e+04,0.000000e+00,0.122920,19.827894,7.352941e+03,2.000000e+06
Min Packet Length,2830743.0,1.643450e+01,2.523772e+01,0.000000e+00,0.000000,2.000000,3.600000e+01,1.448000e+03
Max Packet Length,2830743.0,9.504024e+02,2.028229e+03,0.000000e+00,6.000000,87.000000,5.250000e+02,2.482000e+04
Packet Length Mean,2830743.0,1.719444e+02,3.054915e+02,0.000000e+00,6.000000,57.200000,1.198000e+02,3.337143e+03
Packet Length Std,2830743.0,2.949756e+02,6.318001e+02,0.000000e+00,0.000000,25.980762,1.743239e+02,4.731522e+03
Packet Length Variance,2830743.0,4.861548e+05,1.647490e+06,0.000000e+00,0.000000,675.000000,3.038884e+04,2.240000e+07
FIN Flag Count,2830743.0,3.537976e-02,1.847378e-01,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
SYN Flag Count,2830743.0,4.644646e-02,2.104500e-01,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
RST Flag Count,2830743.0,2.423392e-04,1.556536e-02,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
PSH Flag Count,2830743.0,2.980705e-01,4.574107e-01,0.000000e+00,0.000000,0.000000,1.000000e+00,1.000000e+00
ACK Flag Count,2830743.0,3.158443e-01,4.648513e-01,0.000000e+00,0.000000,0.000000,1.000000e+00,1.000000e+00
URG Flag Count,2830743.0,9.482316e-02,2.929706e-01,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
CWE Flag Count,2830743.0,1.112782e-04,1.054826e-02,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
ECE Flag Count,2830743.0,2.433990e-04,1.559935e-02,0.000000e+00,0.000000,0.000000,0.000000e+00,1.000000e+00
Down/Up Ratio,2830743.0,6.835004e-01,6.804920e-01,0.000000e+00,0.000000,1.000000,1.000000e+00,1.560000e+02
Average Packet Size,2830743.0,1.919837e+02,3.318603e+02,0.000000e+00,7.500000,72.250000,1.492639e+02,3.893333e+03
Avg Fwd Segment Size,2830743.0,5.820194e+01,1.860912e+02,0.000000e+00,6.000000,34.000000,5.000000e+01,5.940857e+03
Avg Bwd Segment Size,2830743.0,3.059493e+02,6.052568e+02,0.000000e+00,0.000000,72.000000,1.810000e+02,5.800500e+03
Fwd Header Length.1,2830743.0,-2.599739e+04,2.105286e+07,-3.221223e+10,40.000000,64.000000,1.200000e+02,4.644908e+06
Fwd Avg Bytes/Bulk,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Fwd Avg Packets/Bulk,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Fwd Avg Bulk Rate,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Bwd Avg Bytes/Bulk,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Bwd Avg Packets/Bulk,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Bwd Avg Bulk Rate,2830743.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00
Subflow Fwd Packets,2830743.0,9.361160e+00,7.496728e+02,1.000000e+00,2.000000,2.000000,5.000000e+00,2.197590e+05
Subflow Fwd Bytes,2830743.0,5.492919e+02,9.980070e+03,0.000000e+00,12.000000,62.000000,1.870000e+02,1.287034e+07
Subflow Bwd Packets,2830743.0,1.039377e+01,9.973883e+02,0.000000e+00,1.000000,2.000000,4.000000e+00,2.919220e+05
Subflow Bwd Bytes,2830743.0,1.616230e+04,2.263057e+06,0.000000e+00,0.000000,123.000000,4.820000e+02,6.554530e+08
Init_Win_bytes_forward,2830743.0,6.989837e+03,1.433873e+04,-1.000000e+00,-1.000000,251.000000,8.192000e+03,6.553500e+04
Init_Win_bytes_backward,2830743.0,1.989433e+03,8.456883e+03,-1.000000e+00,-1.000000,-1.000000,2.350000e+02,6.553500e+04
act_data_pkt_fwd,2830743.0,5.418218e+00,6.364257e+02,0.000000e+00,0.000000,1.000000,2.000000e+00,2.135570e+05
min_seg_size_forward,2830743.0,-2.741688e+03,1.084989e+06,-5.368707e+08,20.000000,24.000000,3.200000e+01,1.380000e+02
Active Mean,2830743.0,8.155132e+04,6.485999e+05,0.000000e+00,0.000000,0.000000,0.000000e+00,1.100000e+08
Active Std,2830743.0,4.113412e+04,3.933815e+05,0.000000e+00,0.000000,0.000000,0.000000e+00,7.420000e+07
Active Max,2830743.0,1.531825e+05,1.025825e+06,0.000000e+00,0.000000,0.000000,0.000000e+00,1.100000e+08
Active Min,2830743.0,5.829582e+04,5.770923e+05,0.000000e+00,0.000000,0.000000,0.000000e+00,1.100000e+08
Idle Mean,2830743.0,8.316037e+06,2.363008e+07,0.000000e+00,0.000000,0.000000,0.000000e+00,1.200000e+08
Idle Std,2830743.0,5.038439e+05,4.602984e+06,0.000000e+00,0.000000,0.000000,0.000000e+00,7.690000e+07
Idle Max,2830743.0,8.695752e+06,2.436689e+07,0.000000e+00,0.000000,0.000000,0.000000e+00,1.200000e+08
Idle Min,2830743.0,7.920031e+06,2.336342e+07,0.000000e+00,0.000000,0.000000,0.000000e+00,1.200000e+08

# 3.10 Memory Usage

In [27]:
df.memory_usage(deep=True).sum()/1024**2

np.float64(1833.9173212051392)

# Step 4: Data Cleaning

## 4.1 Remove Duplicate Rows

In [28]:
print("Before:", df.shape)

duplicates = df.duplicated().sum()
print("Duplicate Rows:", duplicates)

Before: (2830743, 79)
Duplicate Rows: 308381

In [29]:
df = df.drop_duplicates()

print("After:", df.shape)

After: (2522362, 79)

## 4.2 Clean Column Names

In [31]:
df.columns = df.columns.str.strip()

In [32]:
print(df.columns.tolist())

['Destination Port', 'Flow Duration', 'Total Fwd Packets', 'Total Backward Packets', 'Total Length of Fwd Packets', 'Total Length of Bwd Packets', 'Fwd Packet Length Max', 'Fwd Packet Length Min', 'Fwd Packet Length Mean', 'Fwd Packet Length Std', 'Bwd Packet Length Max', 'Bwd Packet Length Min', 'Bwd Packet Length Mean', 'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags', 'Bwd URG Flags', 'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s', 'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length', 'Packet Length Mean', 'Packet Length Std', 'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count', 'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count', 'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count', 'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size', 'Avg Bwd Segment Size', 'Fwd Header Length.1', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate', 'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets', 'Subflow Bwd Bytes', 'Init_Win_bytes_forward', 'Init_Win_bytes_backward', 'act_data_pkt_fwd', 'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label']

## 4.3 Replace Infinite Values

In [33]:
numeric_df = df.select_dtypes(include=np.number)

print(np.isinf(numeric_df).sum().sort_values(ascending=False))

Flow Packets/s                 1564
Flow Bytes/s                   1211
Total Fwd Packets                 0
Total Backward Packets            0
Destination Port                  0
Flow Duration                     0
Fwd Packet Length Max             0
Fwd Packet Length Min             0
Fwd Packet Length Mean            0
Fwd Packet Length Std             0
Bwd Packet Length Max             0
Bwd Packet Length Min             0
Total Length of Fwd Packets       0
Total Length of Bwd Packets       0
Bwd Packet Length Std             0
Bwd Packet Length Mean            0
Flow IAT Mean                     0
Flow IAT Std                      0
Flow IAT Max                      0
Flow IAT Min                      0
Fwd IAT Total                     0
Fwd IAT Mean                      0
Fwd IAT Std                       0
Fwd IAT Max                       0
Fwd IAT Min                       0
Bwd IAT Total                     0
Bwd IAT Mean                      0
Bwd IAT Std                       0
Bwd IAT Max                       0
Bwd IAT Min                       0
Fwd PSH Flags                     0
Bwd PSH Flags                     0
Fwd URG Flags                     0
Bwd URG Flags                     0
Fwd Header Length                 0
Bwd Header Length                 0
Fwd Packets/s                     0
Bwd Packets/s                     0
Min Packet Length                 0
Max Packet Length                 0
Packet Length Mean                0
Packet Length Std                 0
Packet Length Variance            0
FIN Flag Count                    0
SYN Flag Count                    0
RST Flag Count                    0
PSH Flag Count                    0
ACK Flag Count                    0
URG Flag Count                    0
CWE Flag Count                    0
ECE Flag Count                    0
Down/Up Ratio                     0
Average Packet Size               0
Avg Fwd Segment Size              0
Avg Bwd Segment Size              0
Fwd Header Length.1               0
Fwd Avg Bytes/Bulk                0
Fwd Avg Packets/Bulk              0
Fwd Avg Bulk Rate                 0
Bwd Avg Bytes/Bulk                0
Bwd Avg Packets/Bulk              0
Bwd Avg Bulk Rate                 0
Subflow Fwd Packets               0
Subflow Fwd Bytes                 0
Subflow Bwd Packets               0
Subflow Bwd Bytes                 0
Init_Win_bytes_forward            0
Init_Win_bytes_backward           0
act_data_pkt_fwd                  0
min_seg_size_forward              0
Active Mean                       0
Active Std                        0
Active Max                        0
Active Min                        0
Idle Mean                         0
Idle Std                          0
Idle Max                          0
Idle Min                          0
dtype: int64

In [34]:
df.replace([np.inf, -np.inf], np.nan, inplace=True)

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,Bwd Packet Length Max,Bwd Packet Length Min,Bwd Packet Length Mean,Bwd Packet Length Std,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min,Fwd PSH Flags,Bwd PSH Flags,Fwd URG Flags,Bwd URG Flags,Fwd Header Length,Bwd Header Length,Fwd Packets/s,Bwd Packets/s,Min Packet Length,Max Packet Length,Packet Length Mean,Packet Length Std,Packet Length Variance,FIN Flag Count,SYN Flag Count,RST Flag Count,PSH Flag Count,ACK Flag Count,URG Flag Count,CWE Flag Count,ECE Flag Count,Down/Up Ratio,Average Packet Size,Avg Fwd Segment Size,Avg Bwd Segment Size,Fwd Header Length.1,Fwd Avg Bytes/Bulk,Fwd Avg Packets/Bulk,Fwd Avg Bulk Rate,Bwd Avg Bytes/Bulk,Bwd Avg Packets/Bulk,Bwd Avg Bulk Rate,Subflow Fwd Packets,Subflow Fwd Bytes,Subflow Bwd Packets,Subflow Bwd Bytes,Init_Win_bytes_forward,Init_Win_bytes_backward,act_data_pkt_fwd,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,54865,3,2,0,12,0,6,6,6.0,0.00000,0,0,0.0,0.0,4.000000e+06,666666.666700,3.0,0.000000,3,3,3,3.00000,0.00000,3,3,0,0.0,0.0,0,0,0,0,0,0,40,0,666666.666700,0.000000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,0,0,0,0,9.000000,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,33,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1,55054,109,1,1,6,6,6,6,6.0,0.00000,6,6,6.0,0.0,1.100917e+05,18348.623850,109.0,0.000000,109,109,0,0.00000,0.00000,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,9174.311927,9174.311927,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,1,9.000000,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,29,256,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2,55055,52,1,1,6,6,6,6,6.0,0.00000,6,6,6.0,0.0,2.307692e+05,38461.538460,52.0,0.000000,52,52,0,0.00000,0.00000,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,19230.769230,19230.769230,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,1,9.000000,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,29,256,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,46236,34,1,1,6,6,6,6,6.0,0.00000,6,6,6.0,0.0,3.529412e+05,58823.529410,34.0,0.000000,34,34,0,0.00000,0.00000,0,0,0,0.0,0.0,0,0,0,0,0,0,20,20,29411.764710,29411.764710,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,1,0,0,1,9.000000,6.0,6.0,20,0,0,0,0,0,0,1,6,1,6,31,329,0,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
4,54863,3,2,0,12,0,6,6,6.0,0.00000,0,0,0.0,0.0,4.000000e+06,666666.666700,3.0,0.000000,3,3,3,3.00000,0.00000,3,3,0,0.0,0.0,0,0,0,0,0,0,40,0,666666.666700,0.000000,6,6,6.000000,0.000000,0.000000,0,0,0,0,1,0,0,0,0,9.000000,6.0,0.0,40,0,0,0,0,0,0,2,12,0,0,32,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2830738,53,32215,4,2,112,152,28,28,28.0,0.00000,76,76,76.0,0.0,8.194940e+03,186.248642,6443.0,13617.579480,30780,3,30832,10277.33333,17755.84381,30780,4,3,3.0,0.0,3,3,0,0,0,0,80,64,124.165761,62.082881,28,76,41.714286,23.421602,548.571429,0,0,0,0,0,0,0,0,0,48.666667,28.0,76.0,80,0,0,0,0,0,0,4,112,2,152,-1,-1,3,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2830739,53,324,2,2,84,362,42,42,42.0,0.00000,181,181,181.0,0.0,1.376543e+06,12345.679010,108.0,183.597386,320,2,2,2.00000,0.00000,2,2,2,2.0,0.0,2,2,0,0,0,0,40,40,6172.839506,6172.839506,42,181,97.600000,76.133435,5796.300000,0,0,0,0,0,0,0,0,1,122.000000,42.0,181.0,40,0,0,0,0,0,0,2,84,2,362,-1,-1,1,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2830740,58030,82,2,1,31,6,31,0,15.5,21.92031,6,6,6.0,0.0,4.512195e+05,36585.365850,41.0,52.325902,78,4,4,4.00000,0.00000,4,4,0,0.0,0.0,0,0,1,0,0,0,64,20,24390.243900,12195.121950,0,31,17.000000,16.350331,267.333333,0,1,0,0,1,0,0,0,0,22.666667,15.5,6.0,64,0,0,0,0,0,0,2,31,1,6,1006,0,0,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2830741,53,1048635,6,2,192,256,32,32,32.0,0.00000,128,128,128.0,0.0,4.272221e+02,7.628965,149805.0,375521.040500,1000947,1,1033613,206722.60000,444210.06860,1000947,1,3,3.0,0.0,3,3,0,0,0,0,120,40,5.721724,1.907241,32,128,53.333333,42.332021,1792.000000,0,0,0,0,0,0,0,0,0,60.000000,32.0,128.0,120,0,0,0,0,0,0,6,192,2,256,-1,-1,5,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2830742,53,94939,4,2,188,226,47,47,47.0,0.00000,113,113,113.0,0.0,4.360695e+03,63.198475,18987.8,31664.102560,73049,1,73051,24350.33333,42174.28246,73049,1,48,48.0,0.0,48,48,0,0,0,0,104,64,42.132317,21.066158,47,113,65.857143,32.204702,1037.142857,0,0,0,0,0,0,0,0,0,76.833333,47.0,113.0,104,0,0,0,0,0,0,4,188,2,226,-1,-1,3,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

In [35]:
print(np.isinf(df.select_dtypes(include=np.number)).sum().sum())

0

## 4.4 Handle Missing Values

In [36]:
missing = df.isnull().sum()

missing = missing[missing > 0]

print(missing)

Flow Bytes/s      1564
Flow Packets/s    1564
dtype: int64

In [37]:
df.dropna(inplace=True)

In [38]:
print(df.isnull().sum().sum())

0

## 4.5 Remove Constant Features

In [39]:
constant_columns = []

for col in df.columns:
    if df[col].nunique() == 1:
        constant_columns.append(col)

print(constant_columns)

['Bwd PSH Flags', 'Bwd URG Flags', 'Fwd Avg Bytes/Bulk', 'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk', 'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate']

In [40]:
df.drop(columns=constant_columns, inplace=True)

## 4.6 Check Data Types

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 2520798 entries, 0 to 2830742
Data columns (total 71 columns):
 #   Column                       Dtype
---  ------                       -----
 0   Destination Port             int64
 1   Flow Duration                int64
 2   Total Fwd Packets            int64
 3   Total Backward Packets       int64
 4   Total Length of Fwd Packets  int64
 5   Total Length of Bwd Packets  int64
 6   Fwd Packet Length Max        int64
 7   Fwd Packet Length Min        int64
 8   Fwd Packet Length Mean       float64
 9   Fwd Packet Length Std        float64
 10  Bwd Packet Length Max        int64
 11  Bwd Packet Length Min        int64
 12  Bwd Packet Length Mean       float64
 13  Bwd Packet Length Std        float64
 14  Flow Bytes/s                 float64
 15  Flow Packets/s               float64
 16  Flow IAT Mean                float64
 17  Flow IAT Std                 float64
 18  Flow IAT Max                 int64
 19  Flow IAT Min                 int64
 20  Fwd IAT Total                int64
 21  Fwd IAT Mean                 float64
 22  Fwd IAT Std                  float64
 23  Fwd IAT Max                  int64
 24  Fwd IAT Min                  int64
 25  Bwd IAT Total                int64
 26  Bwd IAT Mean                 float64
 27  Bwd IAT Std                  float64
 28  Bwd IAT Max                  int64
 29  Bwd IAT Min                  int64
 30  Fwd PSH Flags                int64
 31  Fwd URG Flags                int64
 32  Fwd Header Length            int64
 33  Bwd Header Length            int64
 34  Fwd Packets/s                float64
 35  Bwd Packets/s                float64
 36  Min Packet Length            int64
 37  Max Packet Length            int64
 38  Packet Length Mean           float64
 39  Packet Length Std            float64
 40  Packet Length Variance       float64
 41  FIN Flag Count               int64
 42  SYN Flag Count               int64
 43  RST Flag Count               int64
 44  PSH Flag Count               int64
 45  ACK Flag Count               int64
 46  URG Flag Count               int64
 47  CWE Flag Count               int64
 48  ECE Flag Count               int64
 49  Down/Up Ratio                int64
 50  Average Packet Size          float64
 51  Avg Fwd Segment Size         float64
 52  Avg Bwd Segment Size         float64
 53  Fwd Header Length.1          int64
 54  Subflow Fwd Packets          int64
 55  Subflow Fwd Bytes            int64
 56  Subflow Bwd Packets          int64
 57  Subflow Bwd Bytes            int64
 58  Init_Win_bytes_forward       int64
 59  Init_Win_bytes_backward      int64
 60  act_data_pkt_fwd             int64
 61  min_seg_size_forward         int64
 62  Active Mean                  float64
 63  Active Std                   float64
 64  Active Max                   int64
 65  Active Min                   int64
 66  Idle Mean                    float64
 67  Idle Std                     float64
 68  Idle Max                     int64
 69  Idle Min                     int64
 70  Label                        str
dtypes: float64(24), int64(46), str(1)
memory usage: 1.4 GB

## 4.7 Standardize Labels

In [42]:
df["Label"] = df["Label"].str.strip()

In [43]:
print(df["Label"].unique())

<StringArray>
[                    'BENIGN',                       'DDoS',
                        'Bot',                   'PortScan',
               'Infiltration',   'Web Attack � Brute Force',
           'Web Attack � XSS', 'Web Attack � Sql Injection',
                'FTP-Patator',                'SSH-Patator',
              'DoS slowloris',           'DoS Slowhttptest',
                   'DoS Hulk',              'DoS GoldenEye',
                 'Heartbleed']
Length: 15, dtype: str

## 4.8 Verify Class Distribution

In [44]:
df["Label"].value_counts()

Label
BENIGN                        2095057
DoS Hulk                       172846
DDoS                           128014
PortScan                        90694
DoS GoldenEye                   10286
FTP-Patator                      5931
DoS slowloris                    5385
DoS Slowhttptest                 5228
SSH-Patator                      3219
Bot                              1948
Web Attack � Brute Force         1470
Web Attack � XSS                  652
Infiltration                       36
Web Attack � Sql Injection         21
Heartbleed                         11
Name: count, dtype: int64

In [45]:
(df["Label"].value_counts(normalize=True) * 100).round(2)

Label
BENIGN                        83.11
DoS Hulk                       6.86
DDoS                           5.08
PortScan                       3.60
DoS GoldenEye                  0.41
FTP-Patator                    0.24
DoS slowloris                  0.21
DoS Slowhttptest               0.21
SSH-Patator                    0.13
Bot                            0.08
Web Attack � Brute Force       0.06
Web Attack � XSS               0.03
Infiltration                   0.00
Web Attack � Sql Injection     0.00
Heartbleed                     0.00
Name: proportion, dtype: float64

## 4.9 Final Dataset Check

In [46]:
print(df.shape)

print(df.isnull().sum().sum())

print(df.duplicated().sum())

print(np.isinf(df.select_dtypes(include=np.number)).sum().sum())

(2520798, 71)
0
0
0

## 4.10 Save the Clean Dataset

In [47]:
df.to_csv("dataset/CICIDS2017_Clean.csv", index=False)